title: Hacker101
email: support@hackerone.com
description: >-
  Hacker101 is a free class for web security. Whether you're a programmer with
  an interest in bug bounties or a seasoned security professional, Hacker101
  has something to teach you.
author:
  name: HackerOne
  twitter: Hacker0x01
google_analytics: UA-49905813-8
markdown: kramdown
url: https://www.hacker101.com
twitter:
  username: Hacker0x01
facebook:
  app_id: 345444188982280
github:
  username: Hacker0x01
social:
  links:
    - https://twitter.com/Hacker0x01
    - https://www.facebook.com/Hacker0x01
    - https://www.linkedin.com/company/hackerone
    - https://github.com/Hacker0x01

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:

collections:
  resources:

exclude:
  [
    .bundle,
    .gitignore,
    CNAME,
    Gemfile,
    Gemfile.lock,
    LICENSE,
    node_modules,
    README.md,
    update_bootstrap.sh,
    vendor,
  ]


